# from youtube_transcript_api import YouTubeTranscriptApi

# ytt_api = YouTubeTranscriptApi()

# #VIDEO URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
# video_id = "dQw4w9WgXcQ"
# transcript_list = ytt_api.list(video_id)

# for transcript in transcript_list:
#     #print(transcript.text)
#     print(
#         transcript.video_id,
#         transcript.language,
#         transcript.language_code,
#         # whether it has been manually created or generated by YouTube
#         transcript.is_generated,
#         # whether this transcript can be translated or not
#         transcript.is_translatable,
#         # a list of languages the transcript can be translated to
#         transcript.translation_languages,
#     )
#     print("------TRANSCRIPT:------")
#     print(transcript.fetch())

# from langchain_community.document_loaders import YoutubeLoader
# url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
# loader = YoutubeLoader.from_youtube_url(url, add_video_info=False)
# docs = loader.load()

# print(docs[0].page_content[:500])
# print(docs[0].metadata)

from youtube_transcript_api import YouTubeTranscriptApi
import youtube_transcript_api
from youtube_transcript_api.proxies import GenericProxyConfig


proxies = {
    "http": "http://user:pass@proxy_host:port",
    "https": "http://user:pass@proxy_host:port",
}

ytt_api = YouTubeTranscriptApi(
    proxy_config=GenericProxyConfig(proxies)
)

video_id = "dQw4w9WgXcQ"
transcript = ytt_api.fetch(video_id)
#print(transcript)
#text = " ".join([t["text"] for t in transcript])
#print(text[:500])