from youtube_transcript_api import YouTubeTranscriptApi
from notes_db import save_transcript_line, clear_transcript_collection, clear_notes_collection

# video_id = "UUhy9xSd6zg"
# file_path = 'yt_transcript.txt'

def generate_transcript(video_id: str):
    print("GENERATE TRANSCRIPT CALLED:", video_id)
    clear_transcript_collection()
    clear_notes_collection()

    try:
        ytt_api = YouTubeTranscriptApi()

        transcript_list = ytt_api.list(video_id)
        transcript = transcript_list.find_transcript(['en']) #automatically find manual and automatic transcripts, prioritizing manual.
        fetched_transcript = ""
        # print(
        #     transcript.video_id,
        #     transcript.language,
        #     transcript.language_code,
        #     # whether it has been manually created or generated by YouTube
        #     transcript.is_generated,
        #     # whether this transcript can be translated or not
        #     transcript.is_translatable,
        #     # a list of languages the transcript can be translated to
        #     transcript.translation_languages,
        # )
        

        if transcript.is_generated:
            fetched_transcript = transcript.fetch()
        else:
            fetched_transcript = ytt_api.fetch(video_id)
        
        # with open(file_path, 'w') as f:

        for i, snippet in enumerate(fetched_transcript):
            #f.write(f'{snippet.text}\n')
            save_transcript_line(snippet.text, i)  # Save each line to ChromaDB Cloud

    except Exception as e:
        print(f"An error occurred: {e}")